[package]
name = "aoc-macros"
version = "0.1.0"
authors = ["Rahul Butani <rr.butani@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.53", features = ["derive"] }
quote = "1.0.7"
