[package]
name = "aoc25"
version = "0.0.0"
edition = "2024"

[dependencies]
aoc.workspace = true
derive_more.workspace = true
owo-colors.workspace = true
rand.workspace = true
rayon.workspace = true
smallvec.workspace = true
strum.workspace = true
static_assertions.workspace = true

[features]

[lib]
path = "lib.rs"

[[bin]]
name = "day01"
path = "01/secret_entrance.rs"

[[bin]]
name = "day02"
path = "02/gift_shop.rs"

[[bin]]
name = "day03"
path = "03/lobby.rs"

[[bin]]
name = "day04"
path = "04/printing_department.rs"

[[bin]]
name = "day05"
path = "05/cafeteria.rs"

# [[bin]]
# name = "day06"
# path = "06/guard_gallivant.rs"

# [[bin]]
# name = "day07"
# path = "07/bridge_repair.rs"

# [[bin]]
# name = "day08"
# path = "08/resonant_collinearity.rs"

# [[bin]]
# name = "day09"
# path = "09/disk_fragmenter.rs"

# [[bin]]
# name = "day10"
# path = "10/hoof_it.rs"

# [[bin]]
# name = "day11"
# path = "11/plutonian_pebbles.rs"

# [[bin]]
# name = "day12"
# path = "12/garden_groups.rs"

# [[bin]]
# name = "day13"
# path = "13/claw_contraption.rs"

# [[bin]]
# name = "day14"
# path = "14/restroom_redoubt.rs"

# [[bin]]
# name = "day15"
# path = "15/warehouse_woes.rs"

# [[bin]]
# name = "day16"
# path = "16/reindeer_maze.rs"

# [[bin]]
# name = "day17"
# path = "17/chronospatial_computer.rs"

# [[bin]]
# name = "day18"
# path = "18/ram_run.rs"

# [[bin]]
# name = "day19"
# path = "19/linen_layout.rs"

# [[bin]]
# name = "day20"
# path = "20/race_condition.rs"

# [[bin]]
# name = "day21"
# path = "21/keypad_conundrum.rs"

# [[bin]]
# name = "day22"
# path = "22/monkey_market.rs"

# [[bin]]
# name = "day23"
# path = "23/lan_party.rs"

# [[bin]]
# name = "day24"
# path = "24/crossed_wires.rs"

# [[bin]]
# name = "day25"
# path = "25/code_chronicle.rs"
