[package]
name = "aoc25"
version = "0.0.0"
edition = "2024"

[dependencies]
aoc.workspace = true
derive_more.workspace = true
owo-colors.workspace = true
rand.workspace = true
rayon.workspace = true
smallvec.workspace = true
strum.workspace = true
static_assertions.workspace = true

[features]

[lib]
path = "lib.rs"

[[bin]]
name = "day01"
path = "01/secret_entrance.rs"

[[bin]]
name = "day02"
path = "02/gift_shop.rs"

[[bin]]
name = "day03"
path = "03/lobby.rs"

[[bin]]
name = "day04"
path = "04/printing_department.rs"

[[bin]]
name = "day05"
path = "05/cafeteria.rs"

[[bin]]
name = "day06"
path = "06/trash_compactor.rs"

[[bin]]
name = "day07"
path = "07/labratories.rs"

# [[bin]]
# name = "day08"
# path = "08/resonant_collinearity.rs"

# [[bin]]
# name = "day09"
# path = "09/disk_fragmenter.rs"

# [[bin]]
# name = "day10"
# path = "10/hoof_it.rs"

# [[bin]]
# name = "day11"
# path = "11/plutonian_pebbles.rs"

# [[bin]]
# name = "day12"
# path = "12/garden_groups.rs"
