[package]
name = "aoc"
version = "0.1.0"
authors = ["Rahul Butani <rr.butani@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
reqwest = "0.9.5"
tap = "0.3.0"
http = "0.1.14"
select = "0.4.2"
