#!/usr/bin/env bash

# Expects <name>

set -e

YEAR="$(basename "$(pwd)")"

function dependencies() {
    return 0
}

langs=(rust)

function python() {
    mkdir -p "${1}/Python" && touch "${1}/${2}.py"
}

function rust() {
    mkdir -p "${1}/" && touch "${1}/${2}.rs"
    cat <<-EOF > "${1}/${2}.rs"
	#!/usr/bin/env rustr

	use aoc::*;

	fn main() {
	    let mut aoc = AdventOfCode::new(${YEAR}, ${3});
	    let input: String = aoc.get_input();

	    println!("{}", input);

	    let p1 = 0;
	    println!("{}", p1);
	    // aoc.submit_p1(p1);

	    let p2 = 0;
	    println!("{}", p2);
	    // aoc.submit_p2(p2);
	}
	EOF

    cat <<-EOF >> "${1}/../Cargo.toml"

	[[bin]]
	name = "day${3}"
	path = "${3}/${2}.rs"
	EOF
}

function haskell() {
    mkdir -p "${1}" && touch "${1}/${2}.hs"
}

function scala() {
    mkdir -p "${1}" && touch "${1}/${2}.scala"
}

function elm() {
    mkdir -p "${1}" && touch "${1}/${2}.elm"
}

function elixir() {
    mkdir -p "${1}" && touch "${1}/${2}.exs"
}

function clojure() { :; }

function openEditor() {
    subl "${@}"
}

if [ -z "${1+x}" ]; then
    echo "Give me a name please!"
    exit 2
fi

nom="${1}"

aocDir="$(dirname "$0")/../"
lastDir=$(ls "${aocDir}" | grep -E '^[0-9]{2}$' | sort | tail -1)
day="$(printf "%02d" $((${lastDir##0} + 1)))"
nextDir="${aocDir}/${day}"

#------------------------------------------------------------------------------#

mkdir -p "${nextDir}"

dependencies

for lang in "${langs[@]}"; do
    $lang "${nextDir}" "${nom}" "${day}" || {
        echo "Something broke! Blame $lang ($?)" && exit 2
    }
done

openEditor "${nextDir}"
